timeclock/app/main/views.py
"""
.. module:: main.views.

   :synopsis: Handles all core URL endpoints for the timeclock application
"""

from datetime import datetime

from flask import current_app
from flask import (
    Blueprint,
    render_template,
    flash,
    request,
    url_for,
    redirect,
    session,
    make_response
)
from flask_login import login_required, current_user

from .forms import (
    AdminFilterEventsForm,
    UserFilterEventsForm,
    CreatePayRateForm,
    TimePunchForm,
    ApproveOrDenyForm,
    FilterTimePunchForm,
    ClearForm,
    AddEventForm,
    DeleteEventForm,
    GenerateMultipleTimesheetsForm,
    RequestVacationForm,
    FilterVacationForm,
    ExportForm
)
from .modules import (
    process_clock,
    set_clock_form,
    get_last_clock,
    get_events_by_date,
    get_clocked_in_users,
    get_time_period,
    process_time_periods,
    get_all_tags,
    check_total_clock_count,
    add_event,
    delete_event,
    generate_timesheet,
    generate_timesheets,
    create_csv
)
from .payments import (
    get_payrate_before_or_after,
    calculate_hours_worked
)
from .requests import (
    create_timepunch,
    get_timepunches_for_review,
    get_vacations_for_review,
    approve_or_deny,
    approve_or_deny_vacation
)
from app.database import db
from ..decorators import admin_required
from app.user.models import Pay, User, Vacation
from app.utils import eval_request_bool

main = Blueprint("main", __name__, static_folder="../static")


@main.route('/', methods=['GET', 'POST'])
def index():
    """
    View function for index page. Reroutes to login if user is not logged in.
    :return: index.html contents
    """
    current_app.logger.info('Start function index() [VIEW]')
    if not current_user.is_authenticated:  # Don't pass a form
        current_app.logger.error('Anonymous user visited index. Redirecting to /auth/login...')
        return redirect(url_for('auth.login'))

    if not current_user.validated:
        current_app.logger.info('{} visited index but is not validated. Redirecting to /auth/change_password'.
                                format(current_user.email))
        current_app.logger.info('End function index')
        return redirect(url_for('auth.change_password'))

    form = set_clock_form()
    if form.validate_on_submit():
        if form.note.data is not None and len(form.note.data) > 60:
            flash("Your note cannot exceed 60 characters", category='warning')
            current_app.logger.error('{} submitted a note that exceeded 60 characters'.format(current_user.email))
        else:
            ip = request.environ['REMOTE_ADDR']
            time = datetime.now()

            # Stores the time and the ip clocked in form
            process_clock(form.note.data, ip)
            flash("Clock submission successfully processed", category='success')

    last = get_last_clock()
    last_time = last.time.strftime("%b %d, %Y | %H:%M") if last else ""
    last_type = last.type if last else False
    current_app.logger.info('End function index')
    return render_template('main/index.html',
                           form=set_clock_form(),
                           last_event=last_time,
                           clocked_in_users=get_clocked_in_users(),
                           last_clock_event=last_type
                           )


@main.route('/all_history', methods=['GET', 'POST'])
@login_required
@admin_required
def all_history():
    """
    View function for url/all_history page.
    Contains a form for sorting by username, start date, and end date.
    :return: All user history, sorted (if applicable) with a form for further
    filtering.
    """
    current_app.logger.info('Start function all_history() [VIEW]')

    if 'first_date' not in session:
        current_app.logger.info('\'first_date\' not found in session. Setting to defaults.')
        session['first_date'] = get_time_period('w')[0]
        session['last_date'] = get_time_period('w')[1]
    if 'email' not in session:
        current_app.logger.info('\'email\' not found in session. Setting to defaults.')
        session['email'] = None
    if 'tag_input' not in session:
        current_app.logger.info('\'tag_input\' not found in session. Setting to defaults.')
        session['tag_input'] = 0
    if 'division' not in session:
        current_app.logger.info('\'division\' not found in session. Setting to defaults.')
        session['division'] = None

    if request.referrer and 'all_history' not in request.referrer:
        # If the user is visiting from another page, reset the session email variable
        current_app.logger.info('User is visiting from another page. Setting session[\'email\'] to None')
        session['email'] = None

    form = AdminFilterEventsForm()

    page = request.args.get('page', 1, type=int)

    if form.validate_on_submit() and (form.submit.data or form.last_month.data
                                      or form.this_month.data or form.last_week.data or
                                      form.this_week.data or form.last_day.data or form.this_day.data):
        time_period = process_time_periods(form)
        session['first_date'] = time_period[0]
        session['last_date'] = time_period[1]
        session['email'] = form.email.data
        session['tag_input'] = form.tag.data
        session['division'] = form.division.data
        page = 1

    addform = AddEventForm()
    if addform.validate_on_submit() and addform.add.data:
        if addform.addemail.data == current_user.email:
            flash('Administrators cannot edit their own clock events', 'error')
            return redirect(url_for('main.clear'))
        date_string = addform.add_date.data.strftime('%m/%d/%Y ')
        time_string = addform.add_time.data
        datetime_str = date_string + time_string
        try:
            datetime_obj = datetime.strptime(datetime_str, '%m/%d/%Y %H:%M')
        except ValueError:
            flash('Please make sure your time input is in the format HH:MM', category='error')
            return redirect(url_for('main.all_history'))
        u = User.query.filter_by(email=addform.addemail.data).first()
        add_event(u.id, datetime_obj, (addform.addpunch_type.data == "In"))
        flash("Clock event successfully processed", 'success')
        return redirect(url_for('main.clear'))

    deleteform = DeleteEventForm(request.form)
    if deleteform.validate_on_submit() and request.form.get('event_id', None) and deleteform.delete.data:
        delete_event(request.form['event_id'])
        flash('Event successfully deleted', category='success')
        return redirect(url_for('main.clear'))

    advtimesheetform = GenerateMultipleTimesheetsForm()
    advtimesheetform.emails.choices = [(u.email, u.email) for u in User.query.all()]
    if advtimesheetform.validate_on_submit() and advtimesheetform.gen_timesheets.data:
        # TODO: THIS MESSAGE ISNT FLASHING
        flash('Succesfully generated timesheet(s)', category='success')
        return generate_timesheets(advtimesheetform.emails.data, advtimesheetform.start_date.data,
                                   advtimesheetform.end_date.data)

    current_app.logger.info('Querying (calling get_events_by_date)')
    events_query = get_events_by_date()
    current_app.logger.info('Finished querying')

    exportform = ExportForm()
    if exportform.validate_on_submit() and exportform.export.data:
        flash('Succesfully exported events in query', 'success')
        return create_csv(events_query.all())


    # Pagination
    pagination = events_query.paginate(
        page, per_page=15,
        error_out=False)
    events = pagination.items

    current_app.logger.info('Querying (calling get_all_tags)')
    tags = get_all_tags()
    current_app.logger.info('Finished querying')

    query_has_results = True if events_query.first() else False

    current_app.logger.info('End function all_history()')
    return render_template('main/all_history.html',
                           events=events,
                           form=form,
                           addform=addform,
                           deleteform=deleteform,
                           advtimesheetform=advtimesheetform,
                           exportform=exportform,
                           pagination=pagination,
                           tags=tags,
                           generation_events=events_query.all(),
                           query_has_results=query_has_results
                           )


@main.route('/history', methods=['GET', 'POST'])  # User history
@login_required
def history():
    """
    Shows a user their own history.
    TODO: Make filterable by date
    :return: An html page that contains user history, sorted (if applicable)
    with a form for further filtering.
    """
    current_app.logger.info('Start function all_history()')
    if not current_user.validated:
        current_app.logger.info('{} is not validated. Redirecting to /auth/change_password...'
                                .format(current_user.email))
        return redirect(url_for('auth.change_password'))

    # Explicitly set email session variable to current user's email, as users on the history page
    # should only be able to view their own information
    session['email'] = current_user.email

    form = UserFilterEventsForm()
    page = request.args.get('page', 1, type=int)
    if form.validate_on_submit():
        time_period = process_time_periods(form)
        session['first_date'] = time_period[0]
        session['last_date'] = time_period[1]
        page = 1

    current_app.logger.info('Querying (calling get_events_by_date)')
    events_query = get_events_by_date()
    current_app.logger.info('Finished querying')

    pagination = events_query.paginate(
        page, per_page=15,
        error_out=False)
    events = pagination.items

    current_app.logger.info('Querying (calling get_all_tags)')
    tags = get_all_tags()

timeclock/app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">
        <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
        page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}"> &laquo;
            </a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li{% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_next %}{{ url_for(endpoint,
    page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
{% endmacro %}

timeclock/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}TimeClock{% endblock %}  <!-- title block inherited from bootstrap/base.html -->

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" rel="stylesheet"
          media="screen">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css"
          rel="stylesheet" media="screen">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css.map"
          rel="stylesheet" media="screen">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js">
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}"/>
{% endblock %}

{% block navbar %}  <!-- Navigation base HTML will go here -->
    <div class="navbar navbar-default" role="navigation" style="border-radius: 0; font-family: 'Sofia Pro Soft', 'Trebuchet MS'; -webkit-font-smoothing: antialiased;
    background-color: #2a6496; border-color: #2a6496;">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('main.index') }}" style="color:white">TimeClock Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        {% if current_user.is_administrator() %}
                            <li>
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button"
                                            id="history-dropdown" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="true" style="margin-top:9px; color:white; background-color:#2a6496;
                                      border: 0">
                                        Users
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="history-dropdown">
                                        <li><a href="{{ url_for('auth.admin_register') }}">Register User</a></li>
                                        <li><a href="{{ url_for('main.pay') }}">Create Pay Rate</a></li>
                                        <li><a href="{{ url_for('main.user_list_page') }}">Edit User Information</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li>
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button"
                                            id="history-dropdown" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="true" style="margin-top:9px; color:white; background-color:#2a6496;
                                      border: 0">
                                        History
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="history-dropdown">
                                        <li><a href="{{ url_for('main.history') }}">My History</a></li>
                                        <li><a href="{{ url_for('main.all_history') }}">All History</a></li>
                                    </ul>
                                </div>
                            </li>

                        {% else %}
                            <li><a href="{{ url_for('main.history') }}" style="color:white">History</a></li>
                        {% endif %}
                        <li>
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button"
                                        id="history-dropdown" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="true" style="margin-top:9px; color:white; background-color:#2a6496;
                                      border: 0">
                                    Requests
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="history-dropdown">
                                    <li><a href="{{ url_for('main.request_timepunch') }}">Request Timepunch/Vacation</a></li>
                                    <li><a href="{{ url_for('main.review_timepunch') }}">Review Timepunches</a></li>
                                    <li><a href="{{ url_for('main.review_vacations') }}">Review Vacations</a></li>
                                </ul>
                            </div>
                        </li>

                        <li><a href="{{ url_for('auth.change_password') }}" style="color:white">Change Password</a></li>
                        <li><a href="{{ url_for('auth.logout') }}" style="color:white">Sign Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}" style="color:white">Sign In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container" style="font-family: 'Sofia Pro Soft'; -webkit-font-smoothing: antialiased">
    {% for category, message in get_flashed_messages(with_categories=True) %}
        {% if category == 'error' %}
            <div class="alert alert-danger">
        {% else %}
            <div class="alert alert-{{ category }}">
        {% endif %}
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
    </div>
    {% endfor %}

{% block page_content %}
{% endblock %}
</div>
{% endblock %}



{% block scripts %} <!-- Include any JS scripts here -->
    {{ super() }}
    {{ moment.include_moment() }}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js"></script>
    <script>

        $(function () {
            $("#add_time").timepicker({
                'timeFormat': 'H:i',
                'step': 1
            });

            $('#punch_time').timepicker({
                'timeFormat': 'H:i',
                'step': 1
            });


            $("#first_date").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#last_date").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#add_date").datepicker({
                dateFormat: 'yy-mm-dd'
            });


            $("#punch_date").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#start_date").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#end_date").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#vac_start").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#vac_end").datepicker({
                dateFormat: 'yy-mm-dd'
            });

        });
    </script>
{% endblock %}